version: '3.8'

services:
  test-minio:
    image: minio/minio
    ports:
      - "9002:9000" 
    environment:
      MINIO_ROOT_USER: testuser
      MINIO_ROOT_PASSWORD: testpass123
    tmpfs:
      - /data
    command: server /data
  
  test-redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    tmpfs:
      - /data