# fly.toml app configuration file generated for wellness-api on 2025-06-10T02:02:25Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wellness-api'
primary_region = 'eze'

[build]

[deploy]
  release_command = 'npx prisma migrate deploy'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
